from __future__ import annotations

from .core import CORE_PRETRAIN_SNAPSHOT_PRESETS
from .dedicated import DEDICATED_PRETRAIN_SNAPSHOT_PRESETS
from .eval import EVAL_PRETRAIN_SNAPSHOT_PRESETS
from .legacy import LEGACY_PRETRAIN_SNAPSHOT_PRESETS
from .smoke import SMOKE_PRETRAIN_SNAPSHOT_PRESETS

PRETRAIN_SNAPSHOT_PRESETS = [
    *CORE_PRETRAIN_SNAPSHOT_PRESETS,
    *DEDICATED_PRETRAIN_SNAPSHOT_PRESETS,
    *LEGACY_PRETRAIN_SNAPSHOT_PRESETS,
    *EVAL_PRETRAIN_SNAPSHOT_PRESETS,
    *SMOKE_PRETRAIN_SNAPSHOT_PRESETS,
]
