_QUESTION_HEADERS = [
    "Question:",
    "Question to answer:",
    "Here is the question:",
    "Answer this question:",
    "Question presented:",
    "Query:",
    "Query to answer:",
    "Please consider this question:",
    "Question under consideration:",
    "The question is:",
]

_CHOICE_HEADERS = [
    "Choices:",
    "Options:",
    "Answer choices:",
    "Available options:",
    "Candidate answers:",
    "Possible answers:",
    "Choices to consider:",
    "Response options:",
    "Available choices:",
    "Select from these options:",
]

_SENTENCE_HEADERS = [
    "Sentence:",
    "Sentence to complete:",
    "Incomplete sentence:",
    "Statement with a blank:",
    "Text containing the blank:",
    "Completion context:",
    "Target sentence:",
    "Fill-in-the-blank sentence:",
    "Sentence under consideration:",
    "Context sentence:",
]

_PASSAGE_HEADERS = [
    "Passage:",
    "Reference passage:",
    "Source passage:",
    "Provided passage:",
    "Supporting passage:",
    "Reading passage:",
    "Reference text:",
    "Source text:",
    "Evidence from the passage:",
    "Context passage:",
]

_GOAL_HEADERS = [
    "Goal:",
    "Objective:",
    "Task objective:",
    "Desired outcome:",
    "Target outcome:",
    "What to accomplish:",
    "Practical goal:",
    "Objective to achieve:",
    "Requested result:",
    "Aim:",
]

_CHOICE_QA_INSTRUCTIONS = [
    "Answer with the best option text.",
    "Select the best answer and reply with its full text.",
    "Choose the correct option and return the option text.",
    "Respond with the complete text of the best choice.",
    "Give the text of the option that best answers the question.",
    "Pick the most appropriate answer and write it out in full.",
    "Return the best choice as text, not as a label.",
    "Identify the correct choice and answer with its wording.",
    "Reply using the full text of the correct option.",
    "Choose the strongest answer and provide its complete text.",
    "State the wording of the best available option.",
    "Answer by copying the full text of the correct choice.",
    "Select one option and respond with the option itself.",
    "Provide the complete answer text for the correct choice.",
    "Pick the best option and return its wording only.",
    "Write out the answer choice that is correct.",
    "Give the full option text that resolves the question.",
    "Respond with the wording of the most suitable choice.",
    "Choose the right answer and state the answer text.",
    "Return the correct option's full text.",
]

_CHOICE_NUMBER_INSTRUCTIONS = [
    "Answer with the number of the best option.",
    "Select the correct choice and reply with its number only.",
    "Return only the number of the best answer.",
    "Choose the right option and provide its number.",
    "Respond with the number assigned to the correct choice.",
    "Identify the best option and answer using only its number.",
    "Give the number of the option that best answers the question.",
    "Pick the most suitable choice and return its number only.",
    "Reply with the correct option number, without its text.",
    "State only the number corresponding to the best choice.",
    "Provide just the number of the correct response.",
    "Choose the best answer and output its option number only.",
    "Return the numeric position of the correct choice.",
    "Answer using the number attached to the best option.",
    "Select the correct response and state only its number.",
    "Give the option number that identifies the best answer.",
    "Reply solely with the number of the selected choice.",
    "Indicate the correct choice by its number and nothing else.",
    "Pick the strongest option and write only its number.",
    "Output the number corresponding to the correct option.",
]
