_BOOLQ_INSTRUCTIONS = [
    "Answer with yes or no.",
    "Based on the passage, reply yes or no.",
    "Give a yes-or-no answer supported by the passage.",
    "Respond only with yes or no.",
    "Use the passage to decide whether the answer is yes or no.",
    "Determine from the text whether to answer yes or no.",
    "Return yes or no according to the passage.",
    "Read the passage and provide a yes-or-no answer.",
    "Answer the question with either yes or no.",
    "State yes or no based on the information above.",
    "Decide whether the passage supports a yes or no answer.",
    "Give the appropriate binary answer: yes or no.",
    "Reply yes or no using the passage as evidence.",
    "From the passage, determine the correct yes-or-no response.",
    "Provide only the correct answer, yes or no.",
    "Judge the question from the text and answer yes or no.",
    "Use the supplied passage to return yes or no.",
    "Indicate the answer with a single yes or no.",
    "Answer directly with yes or no, as supported by the text.",
    "Choose between yes and no using the passage.",
]

_EN_FIRST_TEXT_HEADERS = [
    "Sentence 1:",
    "First sentence:",
    "Sentence A:",
    "First text:",
    "Text A:",
    "Initial sentence:",
    "First passage:",
    "Passage A:",
    "First example:",
    "Example A:",
]
_EN_SECOND_TEXT_HEADERS = [
    "Sentence 2:",
    "Second sentence:",
    "Sentence B:",
    "Second text:",
    "Text B:",
    "Other sentence:",
    "Second passage:",
    "Passage B:",
    "Second example:",
    "Example B:",
]
_EN_TARGET_WORD_HEADERS = [
    "Target word:",
    "Word to compare:",
    "Word under consideration:",
    "Selected word:",
    "Word whose sense must be compared:",
    "Lexical target:",
    "Focus word:",
    "Word to examine:",
    "Term under consideration:",
    "Target term:",
]
_EN_PAWS_QUESTIONS = [
    "Do these two sentences have the same meaning?",
    "Are the two sentences paraphrases of each other?",
    "Do both sentences express the same idea?",
    "Are these sentences semantically equivalent?",
    "Does the second sentence preserve the meaning of the first?",
    "Would these sentences be considered paraphrases?",
    "Is the meaning of the first sentence equivalent to that of the second?",
    "Do the two texts communicate the same meaning?",
    "Are the statements equivalent in meaning?",
    "Is one sentence a paraphrase of the other?",
]
_EN_WIC_QUESTIONS = [
    "Is the target word used with the same meaning in both sentences?",
    "Does the target word have the same sense in the two sentences?",
    "Is the meaning of the target word identical across both contexts?",
    "Does the selected word express the same sense in each sentence?",
    "Is the target term being used in the same way in both texts?",
    "Do both sentences use the focus word with the same meaning?",
    "Is the lexical sense of the target word the same in both examples?",
    "Does the word under consideration retain its meaning across the two sentences?",
    "Are the two occurrences of the target word semantically equivalent?",
    "Is the target word used in one shared sense in these contexts?",
]
_EN_BINARY_INSTRUCTIONS = [
    "Answer yes or no.",
    "Respond only with yes or no.",
    "Give a yes-or-no answer.",
    "Return either yes or no.",
    "Choose between yes and no.",
    "Provide the correct binary label: yes or no.",
    "State yes or no as the answer.",
    "Reply with a single yes or no.",
    "Indicate the answer using yes or no.",
    "Use only yes or no in the response.",
]

_FR_FIRST_TEXT_HEADERS = [
    "Phrase 1 :",
    "Première phrase :",
    "Phrase A :",
    "Premier texte :",
    "Texte A :",
    "Phrase initiale :",
    "Premier passage :",
    "Passage A :",
    "Premier exemple :",
    "Exemple A :",
]
_FR_SECOND_TEXT_HEADERS = [
    "Phrase 2 :",
    "Deuxième phrase :",
    "Phrase B :",
    "Second texte :",
    "Texte B :",
    "Autre phrase :",
    "Second passage :",
    "Passage B :",
    "Deuxième exemple :",
    "Exemple B :",
]
_FR_TARGET_WORD_HEADERS = [
    "Mot cible :",
    "Mot à comparer :",
    "Mot étudié :",
    "Mot sélectionné :",
    "Mot dont le sens doit être comparé :",
    "Cible lexicale :",
    "Mot central :",
    "Mot à examiner :",
    "Terme étudié :",
    "Terme cible :",
]
_FR_WIC_QUESTIONS = [
    "Le mot cible a-t-il le même sens dans les deux phrases ?",
    "Le mot cible est-il employé avec le même sens dans les deux phrases ?",
    "Le sens du mot cible est-il identique dans les deux contextes ?",
    "Le mot sélectionné exprime-t-il le même sens dans chaque phrase ?",
    "Le terme cible est-il utilisé de la même manière dans les deux textes ?",
    "Les deux phrases emploient-elles le mot central avec le même sens ?",
    "Le sens lexical du mot cible est-il le même dans les deux exemples ?",
    "Le mot étudié conserve-t-il son sens entre les deux phrases ?",
    "Les deux occurrences du mot cible sont-elles sémantiquement équivalentes ?",
    "Le mot cible correspond-il à un même sens dans ces deux contextes ?",
]
_FR_BINARY_INSTRUCTIONS = [
    "Réponds par oui ou non.",
    "Réponds uniquement par oui ou non.",
    "Donne une réponse par oui ou non.",
    "Retourne soit oui, soit non.",
    "Choisis entre oui et non.",
    "Fournis le bon libellé binaire : oui ou non.",
    "Indique oui ou non comme réponse.",
    "Réponds avec un seul mot : oui ou non.",
    "Exprime la réponse en utilisant oui ou non.",
    "Utilise uniquement oui ou non dans la réponse.",
]
_FR_CHOICE_NUMBER_INSTRUCTIONS = [
    "Réponds uniquement avec le numéro de la bonne option.",
    "Choisis la bonne réponse et donne son numéro.",
    "Retourne seulement le numéro de la meilleure réponse.",
    "Indique le numéro associé à la bonne option.",
    "Réponds avec le numéro de l'option correcte.",
    "Sélectionne la bonne option et écris uniquement son numéro.",
    "Donne le numéro correspondant à la réponse correcte.",
    "Choisis la meilleure réponse et retourne son numéro seulement.",
    "Indique la bonne réponse par son numéro, sans texte supplémentaire.",
    "Écris uniquement le numéro de l'option sélectionnée.",
]
_FR_CHOICE_LABEL_INSTRUCTIONS = [
    "Réponds avec le libellé de la bonne option.",
    "Choisis la bonne réponse et donne son texte complet.",
    "Retourne le libellé de la meilleure réponse.",
    "Indique le texte associé à la bonne option.",
    "Réponds avec le texte de l'option correcte.",
    "Sélectionne la bonne option et écris son libellé.",
    "Donne le libellé correspondant à la réponse correcte.",
    "Choisis la meilleure réponse et retourne son texte seulement.",
    "Indique la bonne réponse par son libellé, sans numéro.",
    "Écris uniquement le texte de l'option sélectionnée.",
]
