_EN_SUMMARIZATION_INSTRUCTIONS = [
    "Summarize the following article:",
    "Write a concise summary of this article:",
    "Provide a brief summary of the following text:",
    "Condense this article into a short summary:",
    "What is the main point of this article?",
    "Give a one-sentence summary of the following article:",
    "Write an accurate abstract for this text:",
    "Summarize the key information in this article:",
    "Produce a short news summary:",
    "Briefly explain what this article is about:",
    "Create a concise overview of the following text:",
    "TL;DR:",
    "Distill the essential facts from this article:",
    "Capture the most important developments in a short summary:",
    "Write a short, self-contained synopsis of this article:",
    "Summarize what a reader needs to know from this text:",
    "State the core message of the following article:",
    "Compress this article without losing its essential information:",
    "Summarize the following text clearly and accurately:",
    "Give a brief account of the events described below:",
    "Create a concise digest of this article:",
    "Provide a short factual recap of the following text:",
    "Reduce this article to its central facts:",
    "Write a compact summary of the article below:",
    "What is the key takeaway from this article?",
    "Summarize this article for a reader in a hurry:",
    "Reduce the following text to its essentials:",
    "Write a concise and informative summary:",
    "Provide an overview of the key points in this article:",
    "State succinctly what happened in the following article:",
    "Write a short abstract that preserves the main facts:",
    "Present the main ideas of this article concisely:",
    "In summary, what does this article report?",
    "Extract and summarize the article's most important information:",
    "Turn the following article into a brief, accurate summary:",
    "Give the essential content of this article in condensed form:",
]

_FR_SUMMARIZATION_INSTRUCTIONS = [
    "Résumez l’article suivant :",
    "Rédigez un résumé concis de cet article :",
    "Donnez un bref résumé du texte suivant :",
    "Condensez cet article en un court résumé :",
    "Quelle est l’idée principale de cet article ?",
    "Résumez l’article suivant en une phrase :",
    "Rédigez un résumé fidèle de ce texte :",
    "Résumez les informations essentielles de cet article :",
    "Produisez un court résumé journalistique :",
    "Expliquez brièvement de quoi parle cet article :",
    "Créez une synthèse concise du texte suivant :",
    "En bref :",
    "Dégagez les faits essentiels de cet article :",
    "Résumez brièvement les développements les plus importants :",
    "Rédigez un synopsis court et autonome de cet article :",
    "Résumez ce qu’un lecteur doit retenir de ce texte :",
    "Énoncez le message central de l’article suivant :",
    "Condensez cet article sans perdre les informations essentielles :",
    "Résumez le texte suivant avec clarté et précision :",
    "Donnez un bref compte rendu des événements décrits ci-dessous :",
    "Créez un condensé concis de cet article :",
    "Fournissez une courte récapitulation factuelle du texte suivant :",
    "Réduisez cet article à ses faits principaux :",
    "Rédigez un résumé compact de l’article ci-dessous :",
    "Quel est le principal enseignement de cet article ?",
    "Résumez cet article pour un lecteur pressé :",
    "Réduisez le texte suivant à l’essentiel :",
    "Rédigez un résumé concis et informatif :",
    "Présentez les points clés de cet article :",
    "Indiquez succinctement ce qui s’est passé dans l’article suivant :",
    "Rédigez un court résumé qui préserve les faits principaux :",
    "Présentez les idées principales de cet article de façon concise :",
    "En résumé, que rapporte cet article ?",
    "Extrayez et résumez les informations les plus importantes de cet article :",
    "Transformez l’article suivant en un résumé bref et fidèle :",
    "Donnez l’essentiel de cet article sous une forme condensée :",
]

_FR_HEADLINE_INSTRUCTIONS = [
    "Donnez un titre à l’article suivant :",
    "Rédigez un titre concis pour cet article :",
    "Proposez un titre informatif pour le texte suivant :",
    "Quel titre donneriez-vous à cet article ?",
    "Écrivez le titre journalistique de cet article :",
    "Produisez un titre bref qui résume l’information principale :",
    "Créez un titre fidèle au contenu de l’article suivant :",
    "Formulez un titre clair et concis pour ce texte :",
    "Résumez l’article suivant sous la forme d’un titre :",
    "Rédigez une manchette pour l’article ci-dessous :",
    "Trouvez un titre journalistique adapté à cet article :",
    "Proposez une manchette claire pour le contenu suivant :",
    "Donnez à ce texte un titre court et précis :",
    "Formulez le titre qui restitue le mieux le sujet de cet article :",
    "Créez un titre de presse informatif pour le texte ci-dessous :",
    "Rédigez un intitulé bref et fidèle pour cet article :",
    "Quel serait le meilleur titre pour le contenu suivant ?",
    "Produisez une manchette concise qui reflète l’information centrale :",
    "Intitulez l’article suivant de manière claire et informative :",
    "Écrivez un titre qui présente fidèlement le sujet de cet article :",
]
