from __future__ import annotations

from .assistant import ASSISTANT_SFT_SNAPSHOT_PRESETS
from .benchmarks import BENCHMARK_SFT_SNAPSHOT_PRESETS
from .general_knowledge import GENERAL_KNOWLEDGE_SFT_SNAPSHOT_PRESETS
from .legacy import LEGACY_SFT_SNAPSHOT_PRESETS
from .reasoning import REASONING_SFT_SNAPSHOT_PRESETS
from .text_processing import TEXT_PROCESSING_SFT_SNAPSHOT_PRESETS
from .translation import TRANSLATION_SFT_SNAPSHOT_PRESETS

SFT_SNAPSHOT_PRESETS = [
    *ASSISTANT_SFT_SNAPSHOT_PRESETS,
    *BENCHMARK_SFT_SNAPSHOT_PRESETS,
    *GENERAL_KNOWLEDGE_SFT_SNAPSHOT_PRESETS,
    *REASONING_SFT_SNAPSHOT_PRESETS,
    *TEXT_PROCESSING_SFT_SNAPSHOT_PRESETS,
    *TRANSLATION_SFT_SNAPSHOT_PRESETS,
    *LEGACY_SFT_SNAPSHOT_PRESETS,
]
